# This file was generated by Nuitka and describes the types of the
# created shared library.

# At this time it lists only the imports made and can be used by the
# tools that bundle libraries, including Nuitka itself. For instance
# standalone mode usage of the created library will need it.

# In the future, this will also contain type information for values
# in the module, so IDEs will use this. Therefore please include it
# when you make software releases of the extension module that it
# describes.

import abc
import collections
import collections.abc
import contextlib
import enum
import importlib.metadata
import io
import itertools
import operator
import pathlib
import posixpath
import typing
import warnings
import zipfile

import _collections_abc
import importlib_metadata

import ci_plumber.module_attributes

# This is not Python source even if it looks so. Make it clear for
# now. This was decided by PEP 484 designers.
__name__ = ...
