site_name: CI Plumber
theme:
  name: material
  palette:
      scheme: slate
      primary: lime
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    logo: material/pipe
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.expand
    - content.code.annotate
plugins:
  - search
repo_url: https://github.com/pbexe/ci-plumber
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.keys
nav:
  - Home: index.md
  - Installation: installation.md
  - Tutorial: tutorial.md
  - Plugins:
    - Gitlab: gitlab.md
    - OpenShift: openshift.md
    - Azure: azure.md
